{"uuid":"8f05355c-13e6-424a-bd0d-57d770bc20ca","historyId":"d9c37d642190e386d69f9af22f74ff2e","testCaseId":"[engine:junit-jupiter]/[class:com.connection.bufferjsondata.BufferJsonDataServiceImplLondonTest]/[method:shouldThrowExceptionWhenDataAlreadyExists()]","testCaseName":"Add JSON data - Negative: Data already exists","fullName":"com.connection.bufferjsondata.BufferJsonDataServiceImplLondonTest.shouldThrowExceptionWhenDataAlreadyExists","labels":[{"name":"junit.platform.uniqueid","value":"[engine:junit-jupiter]/[class:com.connection.bufferjsondata.BufferJsonDataServiceImplLondonTest]/[method:shouldThrowExceptionWhenDataAlreadyExists()]"},{"name":"host","value":"Yurik"},{"name":"thread","value":"3356652@Yurik.main(1)"},{"name":"framework","value":"junit-platform"},{"name":"language","value":"java"},{"name":"package","value":"com.connection.bufferjsondata.BufferJsonDataServiceImplLondonTest"},{"name":"testClass","value":"com.connection.bufferjsondata.BufferJsonDataServiceImplLondonTest"},{"name":"testMethod","value":"shouldThrowExceptionWhenDataAlreadyExists"},{"name":"suite","value":"Buffer Json Data Service Implementation Tests"}],"links":[],"name":"Add JSON data - Negative: Data already exists","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"\nExpecting actual throwable to be an instance of:\n  com.connection.processing.buffer.objects.json.exception.BufferJsonDataAlreadyExistsException\nbut was:\n  java.lang.SecurityException: Buffer doesn't belong to the authenticated client\n\tat com.connection.bufferjsondata.BufferJsonDataServiceImpl.addJsonData(BufferJsonDataServiceImpl.java:56)\n\tat com.connection.bufferjsondata.BufferJsonDataServiceImplLondonTest.lambda$shouldThrowExceptionWhenDataAlreadyExists$1(BufferJsonDataServiceImplLondonTest.java:131)\n\tat org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:63)\n\t...(77 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)","trace":"java.lang.AssertionError: \nExpecting actual throwable to be an instance of:\n  com.connection.processing.buffer.objects.json.exception.BufferJsonDataAlreadyExistsException\nbut was:\n  java.lang.SecurityException: Buffer doesn't belong to the authenticated client\n\tat com.connection.bufferjsondata.BufferJsonDataServiceImpl.addJsonData(BufferJsonDataServiceImpl.java:56)\n\tat com.connection.bufferjsondata.BufferJsonDataServiceImplLondonTest.lambda$shouldThrowExceptionWhenDataAlreadyExists$1(BufferJsonDataServiceImplLondonTest.java:131)\n\tat org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:63)\n\t...(77 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)\n\tat com.connection.bufferjsondata.BufferJsonDataServiceImplLondonTest.shouldThrowExceptionWhenDataAlreadyExists(BufferJsonDataServiceImplLondonTest.java:132)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\n"},"stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1758335131370,"stop":1758335132785}